config/routes.rb
Rails.application.routes.draw do
  root :to => "articles#index"
  resources :articles
  get 'search', to: 'search#search'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  text       :text
#  created_at :datetime
#  updated_at :datetime
#


class Article < ActiveRecord::Base

  include PgSearch
    pg_search_scope :search, against: [:title, :text],
      using: {tsearch: {dictionary: "english", prefix: true, any_word: true}}

    def self.text_search(query)
      if query.present?
        search(query)
      else
        Article.all
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find params[:id]
  end

  def new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  private
    def article_params
      params.require(:article).permit :title, :text
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:query].nil?
      @articles = []
    else
	  @articles = Article.text_search(params[:query])
	  # render json: @articles
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<form method="get" action="search">
  <p>
    Search for: <input type="text" name="query" placeholder="war and peace">
    <%= submit_tag "Go", name: nil %>
  </p>
</form>

<ul>
  <% @articles.each do |article| %>
    <li>
      <h3>
        <%= article.title %>
      </h3>
      <p>
        <%= article.text %>
      </p>
    </li>
  <% end -%>
</ul>
<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>  

<%= form_for :article, url: articles_path do |f| %>

  <% if not @article.nil? and @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to '<- Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to '<- Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsElasticsearchExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/search.html.erb
<h1>Articles</h1>

<%= link_to 'All Articles', articles_url %>

<form method="get" action="search">
  <p>
    Search for: <input type="text" name="query" placeholder="war and peace">
    <%= submit_tag "Go", name: nil %>
  </p>
</form>

<ul>
  <% @articles.each do |article| %>
    <li>
      <h3>
        <%= link_to article.title,
          controller: "articles",
          action: "show",
          id: article.id%>
      </h3>
      <% if article %>
       <%= article.text %>
      <% end %>
    </li>
  <% end %>
</ul>